// swift-tools-version:5.10
// SPDX-License-Identifier: Apache-2.0
import PackageDescription

let package = Package(
    name: "SimUse",
    platforms: [
        .macOS(.v14)
    ],
    products: [
        .executable(
            name: "sim-use",
            targets: ["SimUse"]
        ),
        .library(
            name: "SimUseCore",
            targets: ["SimUseCore"]
        ),
        .library(
            name: "AndroidBackend",
            targets: ["AndroidBackend"]
        ),
        .library(
            name: "iOSSimBackend",
            targets: ["iOSSimBackend"]
        ),
        .library(
            name: "SimUseKit",
            targets: ["SimUseKit"]
        ),
    ],
    dependencies: [
        .package(url: "https://github.com/apple/swift-argument-parser", from: "1.5.0"),
    ],
    targets: [
        .target(
            name: "SimUseCore",
            dependencies: [
                .product(name: "ArgumentParser", package: "swift-argument-parser"),
            ],
            path: "Sources/SimUseCore",
            // VERSION is consumed by the daemon (DaemonClient version-
            // check gate, DaemonServer ping response). Generating it
            // per-target is cheap and keeps the daemon dependency-free
            // of higher targets.
            plugins: ["VersionPlugin"]
        ),
        .target(
            name: "iOSSimBackend",
            dependencies: [
                "SimUseCore",
                "FBSimulatorControl",
                "FBDeviceControl",
                "FBControlCore",
                "XCTestBootstrap",
                .product(name: "ArgumentParser", package: "swift-argument-parser"),
            ],
            path: "Sources/iOSSimBackend",
            // No `-rpath` here: the executable `SimUse` target owns
            // `@executable_path` at link time, and ld emits a
            // "duplicate -rpath ignored" warning when both targets
            // claim it. Library targets don't load XCFrameworks; only
            // the final executable needs the runtime search path.
            plugins: ["VersionPlugin"]
        ),
        .target(
            name: "AndroidBackend",
            dependencies: [
                "SimUseCore",
                .product(name: "ArgumentParser", package: "swift-argument-parser"),
            ],
            path: "Sources/AndroidBackend",
            // Resources/ holds `sim-use-device-bridge.apk` at runtime
            // (built by `scripts/build-bridge.sh`). Copy the whole
            // directory so the SPM build doesn't require the APK to
            // exist at build time — `AndroidDeviceController` surfaces
            // a clear "Bridge APK not found" error when the resource
            // is missing.
            resources: [
                .copy("Resources"),
            ]
        ),
        .target(
            name: "SimUseKit",
            dependencies: [
                "SimUseCore",
                "iOSSimBackend",
                "AndroidBackend",
                "FBSimulatorControl",
                "FBControlCore",
                .product(name: "ArgumentParser", package: "swift-argument-parser"),
            ],
            path: "Sources/SimUseKit"
        ),
        .executableTarget(
            name: "SimUse",
            dependencies: [
                .product(name: "ArgumentParser", package: "swift-argument-parser"),
                "SimUseCore",
                "AndroidBackend",
                "iOSSimBackend",
                "SimUseKit",
                "FBSimulatorControl",
                "FBDeviceControl",
                "FBControlCore",
                "XCTestBootstrap"
            ],
            path: "Sources/SimUse",
            resources: [
                .copy("Resources/skills"),
                // Built Viewer SPA assets (Vite output). Re-generated by
                // `scripts/build-viewer.sh`; committed so `swift build`
                // works without Node on contributor machines that don't
                // touch the Viewer. The `viewer` subcommand reads this
                // tree via `Bundle.module.resourceURL` and serves it
                // out of a local HTTP listener.
                .copy("Resources/viewer"),
            ],
            swiftSettings: [
                .unsafeFlags(["-parse-as-library"])
            ],
            linkerSettings: [
                // For XCFrameworks, rpath can often be just @executable_path
                // if SPM handles embedding correctly, or you might need to adjust
                // if you manually copy them later for distribution.
                .unsafeFlags([
                    "-Xlinker", "-dead_strip",
                    "-Xlinker", "-headerpad_max_install_names",
                    "-Xlinker", "-rpath", "-Xlinker", "@executable_path" // Simpler rpath for SPM-handled XCFrameworks
                ])
            ],
            plugins: ["VersionPlugin"]
        ),
        .testTarget(
            name: "SimUseTests",
            dependencies: ["SimUse", "iOSSimBackend", "SimUseCore"],
            path: "Tests",
            // `Tests/` is the umbrella path; the sub-target test
            // directories below sit under it as separate testTargets.
            // List them by name in `exclude` so SwiftPM doesn't double-
            // claim their sources. Add new test sub-directories here
            // when adding new testTargets, or move them out from under
            // `Tests/` to drop this maintenance burden.
            exclude: [
                "SimUseCoreTests",
                "AndroidBackendTests",
                "SimUseKitTests",
            ],
            resources: [
                .copy("README.md"),
                .copy("Fixtures")
            ]
        ),
        .testTarget(
            name: "SimUseCoreTests",
            dependencies: ["SimUseCore"],
            path: "Tests/SimUseCoreTests"
        ),
        .testTarget(
            name: "AndroidBackendTests",
            dependencies: ["AndroidBackend", "SimUseCore"],
            path: "Tests/AndroidBackendTests"
            // `Fixtures/` here is empty (`.gitkeep` only) — listing
            // it as a resource would emit a SwiftPM warning. Add a
            // `.copy("Fixtures")` entry when real fixture files
            // land.
        ),
        .testTarget(
            name: "SimUseKitTests",
            dependencies: ["SimUseKit", "SimUseCore"],
            path: "Tests/SimUseKitTests"
        ),
        .plugin(
            name: "VersionPlugin",
            capability: .buildTool(),
            path: "Plugins/VersionPlugin"
        ),
        .binaryTarget(
            name: "FBControlCore",
            url: "https://github.com/kmatsushita1012/sim-use/releases/download/v0.10.1/FBControlCore.xcframework.zip",
            checksum: "93a08dd119a08bee326a00cb57860df6aa3e2989fb621f84d825576390f175c2"
        ),
        .binaryTarget(
            name: "FBDeviceControl",
            url: "https://github.com/kmatsushita1012/sim-use/releases/download/v0.10.1/FBDeviceControl.xcframework.zip",
            checksum: "9bafac5314ccf38bcb780bc60e2c1d218149249c552bb263750bb0870174a0fa"
        ),
        .binaryTarget(
            name: "FBSimulatorControl",
            url: "https://github.com/kmatsushita1012/sim-use/releases/download/v0.10.1/FBSimulatorControl.xcframework.zip",
            checksum: "e59dc11f3f0d602b682f83e262abb5fcf765bfb74bbe9c4d0b1c538a14e9fc6b"
        ),
        .binaryTarget(
            name: "XCTestBootstrap",
            url: "https://github.com/kmatsushita1012/sim-use/releases/download/v0.10.1/XCTestBootstrap.xcframework.zip",
            checksum: "6fd66c9c38dc52ab65d40e84a741d34c1c020fb77829ef0a711bcfc0e03871d8"
        ),
    ]
)
